name: Release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, master]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Release to GitHub
        uses: cycjimmy/semantic-release-action@v2.5.4
        with:
          dry_run: false
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/git
            @semantic-release/github
          branches: |
            ['main']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
